%%
%% Autogenerated by Thrift Compiler (0.9.3)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-module(scrabbleCheat_types).

-include("scrabbleCheat_types.hrl").

-export([struct_info/1, struct_info_ext/1]).

struct_info('tile') ->
  {struct, [{1, byte},
          {2, byte},
          {3, i32},
          {4, string},
          {5, i32}]}
;

struct_info('move') ->
  {struct, [{1, {list, {struct, {'scrabbleCheat_types', 'tile'}}}},
          {2, i16}]}
;

struct_info('turn') ->
  {struct, [{1, {struct, {'scrabbleCheat_types', 'move'}}},
          {2, string}]}
;

struct_info('gameInfo') ->
  {struct, [{1, i32},
          {2, byte},
          {3, {map, byte, i32}},
          {4, {map, string, byte}},
          {5, {map, string, byte}},
          {6, {list, i32}},
          {7, {list, {struct, {'scrabbleCheat_types', 'tile'}}}}]}
;

struct_info('gamestate') ->
  {struct, [{1, {list, {struct, {'scrabbleCheat_types', 'tile'}}}},
          {2, {map, string, i16}},
          {3, string},
          {4, {list, string}},
          {5, {list, {struct, {'scrabbleCheat_types', 'turn'}}}},
          {6, i32},
          {7, i32}]}
;

struct_info('badArgsException') ->
  {struct, [{1, string}]}
;

struct_info(_) -> erlang:error(function_clause).

struct_info_ext('tile') ->
  {struct, [{1, undefined, byte, 'row', undefined},
          {2, undefined, byte, 'col', undefined},
          {3, undefined, i32, 'type', undefined},
          {4, undefined, string, 'letter', undefined},
          {5, undefined, i32, 'bonus', undefined}]}
;

struct_info_ext('move') ->
  {struct, [{1, undefined, {list, {struct, {'scrabbleCheat_types', 'tile'}}}, 'move', []},
          {2, undefined, i16, 'score', undefined}]}
;

struct_info_ext('turn') ->
  {struct, [{1, undefined, {struct, {'scrabbleCheat_types', 'move'}}, 'move', #'move'{}},
          {2, undefined, string, 'player', undefined}]}
;

struct_info_ext('gameInfo') ->
  {struct, [{1, undefined, i32, 'name', undefined},
          {2, undefined, byte, 'rack_size', undefined},
          {3, undefined, {map, byte, i32}, 'bingo_bonus', dict:new()},
          {4, undefined, {map, string, byte}, 'letter_distribution', dict:new()},
          {5, undefined, {map, string, byte}, 'score_distribution', dict:new()},
          {6, undefined, {list, i32}, 'allowed_dictionaries', []},
          {7, undefined, {list, {struct, {'scrabbleCheat_types', 'tile'}}}, 'board_template', undefined}]}
;

struct_info_ext('gamestate') ->
  {struct, [{1, undefined, {list, {struct, {'scrabbleCheat_types', 'tile'}}}, 'board', undefined},
          {2, undefined, {map, string, i16}, 'scores', dict:new()},
          {3, undefined, string, 'player_turn', undefined},
          {4, undefined, {list, string}, 'turn_order', []},
          {5, undefined, {list, {struct, {'scrabbleCheat_types', 'turn'}}}, 'history', []},
          {6, undefined, i32, 'game_name', undefined},
          {7, undefined, i32, 'dict', undefined}]}
;

struct_info_ext('badArgsException') ->
  {struct, [{1, undefined, string, 'reprimand', undefined}]}
;

struct_info_ext(_) -> erlang:error(function_clause).

